name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.CLAUDE_GITHUB_TOKEN }}

          direct_prompt: |
            Please analyze the changes in this PR and focus on identifying critical issues related to:
            - Potential bugs or issues
            - Performance
            - Security
            - Correctness

            If critical issues are found, list them in a few short bullet points. If no critical issues are found, provide a simple approval.
            Sign off with a checkbox emoji:  (approved) or  (issues found).

            Keep your response concise. Only highlight critical issues that must be addressed before merging. Skip detailed style or minor suggestions unless they impact performance, security, or correctness.
